[theme]
primaryColor = "#4A90E2"
backgroundColor = "#030712"
secondaryBackgroundColor = "#111827"
textColor = "#E5E7EB"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
port = 8501
